from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE

OUT='docs/Quick_GIGS_Business_Plan_GTM_Startup_Fund.pptx'
prs=Presentation(); prs.slide_width=Inches(13.333); prs.slide_height=Inches(7.5); blank=prs.slide_layouts[6]
INK=RGBColor(16,16,20); WHITE=RGBColor(255,255,255); MUTED=RGBColor(95,99,104); MINT=RGBColor(0,168,120); LIGHT=RGBColor(234,248,243); LAV=RGBColor(244,240,255); GOLD=RGBColor(255,247,228); LINE=RGBColor(220,226,223)
def box(s,x,y,w,h,fill,round=True):
 sh=s.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE if round else MSO_SHAPE.RECTANGLE, Inches(x), Inches(y), Inches(w), Inches(h)); sh.fill.solid(); sh.fill.fore_color.rgb=fill; sh.line.color.rgb=fill; return sh
def tx(s,x,y,w,h,t,sz=16,col=INK,bold=False,align=PP_ALIGN.LEFT):
 b=s.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h)); tf=b.text_frame; tf.word_wrap=True; p=tf.paragraphs[0]; p.alignment=align; p.space_after=Pt(0); r=p.add_run(); r.text=t; r.font.name='Aptos'; r.font.size=Pt(sz); r.font.bold=bold; r.font.color.rgb=col; return b
def slide(k,title,sub=''):
 s=prs.slides.add_slide(blank); s.background.fill.solid(); s.background.fill.fore_color.rgb=WHITE; box(s,0,0,13.333,.08,MINT,False); tx(s,.65,.35,12,.2,k.upper(),9,MINT,True); tx(s,.65,.7,12,.6,title,28,INK,True); tx(s,.65,1.35,12,.35,sub,11,MUTED); tx(s,.65,7.18,9,.15,'QUICK GIGS • BUSINESS PLAN + GTM + STARTUP FUND • CONFIDENTIAL',7,MUTED,True); tx(s,12.2,7.16,.4,.15,str(len(prs.slides)),8,MUTED,True,PP_ALIGN.RIGHT); return s
def card(s,x,y,w,h,title,body,fill=LIGHT):
 box(s,x,y,w,h,fill); tx(s,x+.2,y+.18,w-.4,.25,title,12,INK,True); tx(s,x+.2,y+.6,w-.4,h-.75,body,10.5,MUTED)
def cover():
 s=prs.slides.add_slide(blank); s.background.fill.solid(); s.background.fill.fore_color.rgb=INK; box(s,0,0,13.333,.1,MINT,False); tx(s,.8,1.0,10,.3,'BUSINESS PLAN + GO-TO-MARKET + STARTUP FUND',11,MINT,True); tx(s,.8,1.55,9,1,'Quick GIGS',46,MINT,True); tx(s,.85,2.85,8.4,.8,'The trusted operating layer between Indian businesses and creative talent.',23,WHITE,True); card(s,8.7,1.5,3.5,3.2,'THE PROMISE','Describe the work.\nGet a verified specialist, a clear price and accountable delivery.',RGBColor(28,42,39)); tx(s,.85,6.5,9,.3,'Lucknow • India-wide remote delivery • Vinayak Tower, Vibhuti Khand, Lucknow 226028',9,RGBColor(185,195,191))
cover()
s=slide('01 / Executive summary','A faster, fairer way to buy creative work','AI-assisted briefs, verified supply, escrow and delivery accountability.'); card(s,.8,2.0,3.7,2.5,'CUSTOMER','Describe a rough requirement and receive a structured brief, verified match and clear checkout.'); card(s,4.8,2.0,3.7,2.5,'CREATOR','Join without a platform fee and receive 100% of the service subtotal after approval.',LAV); card(s,8.8,2.0,3.7,2.5,'BUSINESS','Start with one-off gigs, then expand to monthly plans and managed pods.',GOLD); tx(s,.8,5.25,11.7,.6,'North star: approved, repeatable work delivered on time with a positive rating and fair creator payout.',19,INK,True,PP_ALIGN.CENTER)
s=slide('02 / Problem','Creative work is needed weekly—but buying it is fragmented'); card(s,.8,2.0,2.85,2.8,'BUYER PAIN','Slow hiring\nVague briefs\nUnclear pricing\nRevision loops\nNo overflow capacity'); card(s,3.9,2.0,2.85,2.8,'CREATOR PAIN','Lead chasing\nScope confusion\nPayout anxiety\nLow-quality requests'); card(s,7.0,2.0,2.85,2.8,'AGENCY PAIN','Demand spikes\nSpecialist gaps\nWhite-label pressure\nCoordination cost'); card(s,10.1,2.0,2.35,2.8,'WHY NOW','Short-form content\nCreator economy\nAI coordination\nSMB demand',GOLD)
s=slide('03 / Product workflow','From rough idea to approved delivery'); steps=[('1','Describe','AI structures the request'),('2','Match','Verified specialists'),('3','Order','Subtotal + GST; escrow'),('4','Deliver','Progress and QA'),('5','Approve','Payout after acceptance')]
for i,(n,a,b) in enumerate(steps):
 x=.7+i*2.5; card(s,x,2.35,2.1,2.0,n+'  '+a,b if False else b,LIGHT if i%2==0 else LAV)
tx(s,.8,5.2,11.7,.55,'Customer breakdown: service amount + GST only. Creator receives 100% of the service subtotal.',18,INK,True,PP_ALIGN.CENTER)
s=slide('04 / Beachhead segments','Start narrow around recurring demand'); card(s,.8,2.0,2.85,2.75,'D2C BRANDS','Reels, paid-social creatives, UGC packs and launch content'); card(s,3.9,2.0,2.85,2.75,'AGENCIES','White-label overflow, specialist pods and one delivery record',LAV); card(s,7.0,2.0,2.85,2.75,'REGIONAL SMBs','Starter packages, social presence and low-risk first order',GOLD); card(s,10.1,2.0,2.35,2.75,'CREATOR BUSINESSES','Podcast clips, short-form repurposing and weekly packs')
s=slide('05 / Positioning','A managed marketplace—not a directory','For Indian businesses that need creative work shipped this week, Quick GIGS turns a rough request into a verified match and accountable delivery.'); card(s,1.0,3.0,3.4,1.8,'SPEED','Brief to shortlist in minutes'); card(s,4.95,3.0,3.4,1.8,'TRUST','Verification, escrow and GST clarity',LAV); card(s,8.9,3.0,3.4,1.8,'FAIRNESS','Zero creator fee and 100% subtotal payout',GOLD)
s=slide('06 / Business model','Transparent pricing now; monetisation expands with trust'); card(s,.8,2.0,2.85,2.7,'ONE-OFF GIGS','Starter, Pro and Studio packages'); card(s,3.9,2.0,2.85,2.7,'MONTHLY PLANS','Allowance, seats, SLA and consolidated billing',LAV); card(s,7.0,2.0,2.85,2.7,'MANAGED PODS','Specialists, coordinator and reporting',GOLD); card(s,10.1,2.0,2.35,2.7,'FUTURE','Customer-side fee, add-ons and priority matching after proof')
s=slide('07 / Pricing and payout','The creator promise is a growth advantage'); card(s,.9,2.0,3.5,2.3,'ILLUSTRATIVE ORDER','Service subtotal: ₹2,500\nGST example: ₹450\nCustomer pays: ₹2,950'); card(s,4.9,2.0,3.5,2.3,'CREATOR','Receives: ₹2,500\nPlatform fee: ₹0\nNo creator deduction',LAV); card(s,8.9,2.0,3.5,2.3,'RULE','Keep GST separate. Do not show a customer platform fee while the setting is disabled.',GOLD)
s=slide('08 / GTM thesis','Concierge first. Proof second. Scale third'); card(s,.8,2.0,2.25,2.5,'WEEKS 1–2','Instrument funnel, CRM, QA and creator verification'); card(s,3.25,2.0,2.25,2.5,'WEEKS 3–8','Founder-led matching and paid pilot',LAV); card(s,5.7,2.0,2.25,2.5,'MONTHS 3–4','Case studies, proof and referrals'); card(s,8.15,2.0,2.25,2.5,'MONTHS 5–8','Partnerships, SEO/AEO and lifecycle'); card(s,10.6,2.0,2.0,2.5,'MONTHS 9–12','Pods and validated paid scale',GOLD)
s=slide('09 / Channel plan','Five channels, each with a distinct job'); card(s,.8,2.0,3.7,2.4,'OUTBOUND + REFERRALS','Founder outreach to D2C brands and agencies. Ask for referrals after approved delivery.'); card(s,4.8,2.0,3.7,2.4,'PARTNERSHIPS','Coworking spaces, accelerators, consultants and agency networks.',LAV); card(s,8.8,2.0,3.7,2.4,'SEO + PROOF + PAID','Outcome-led pages, delivered-work stories and small paid tests only after validation.',GOLD)
s=slide('10 / Funnel KPIs','Measure approved, repeatable work—not signups'); card(s,.8,2.0,2.8,2.5,'LEAD QUALITY','Qualified lead rate ≥50%'); card(s,3.85,2.0,2.8,2.5,'CONVERSION','Qualified to order 15–30% pilot benchmark',LAV); card(s,6.9,2.0,2.8,2.5,'DELIVERY','Match under 15 min; on-time ≥90%',GOLD); card(s,9.95,2.0,2.5,2.5,'RETENTION','4.6/5 rating; 35% repeat in 90 days')
s=slide('11 / Supply strategy','Demand and supply grow together'); card(s,.8,2.0,3.7,2.8,'RECRUIT','LinkedIn, Instagram, referrals, creator groups and agencies.'); card(s,4.8,2.0,3.7,2.8,'VERIFY','Portfolio, category fit, availability, rate and turnaround.',LAV); card(s,8.8,2.0,3.7,2.8,'RETAIN','Clear scope, fair revisions, repeat demand and 100% subtotal payout.',GOLD)
s=slide('12 / 90-day execution','Prove the loop before buying scale'); card(s,.8,2.0,5.7,1.6,'DAYS 1–30','Choose three packages, verify 30–40 creators, contact 100 businesses and complete first 10 orders.'); card(s,6.85,2.0,5.7,1.6,'DAYS 31–60','Reach 30 paid orders, publish proof, start referrals and identify the best segment.',LAV); card(s,.8,4.0,5.7,1.6,'DAYS 61–90','Test SEO/AEO, one partnership and one paid-intent campaign.'); card(s,6.85,4.0,5.7,1.6,'EXIT CRITERIA','30 orders • ≥80% on-time • 10 repeat opportunities • 5 case studies',GOLD)
s=slide('13 / Startup fund','Recommended funding: ₹35–50 lakh for a lean 12-month launch','Use ₹15–20 lakh first if founder runway allows a 4–6 month validation pilot.'); card(s,.8,2.0,3.7,2.9,'LEAN PILOT','₹18 lakh / 6 months\nFounder + operations: ₹5L\nProduct: ₹3L\nSales: ₹2.5L\nSupply/QA: ₹2.75L\nOther + contingency: ₹4.75L',LIGHT); card(s,4.8,2.0,3.7,2.9,'BASE PLAN','₹42 lakh / 12 months\nTeam: ₹14L\nProduct: ₹7L\nAcquisition: ₹6L\nSupply/ops: ₹7L\nLegal/tools/contingency: ₹8L',LAV); card(s,8.8,2.0,3.7,2.9,'GROWTH ROUND','₹75L–₹1Cr only after proof\nScale sales, engineering, supply, partnerships and validated paid channels.',GOLD)
s=slide('14 / Funding allocation','Where the base ₹42 lakh goes'); cats=[('Team + founders','₹14L'),('Product + engineering','₹7L'),('Sales + acquisition','₹6L'),('Supply + quality','₹4L'),('Content + brand','₹3L'),('Support + operations','₹3L'),('Legal + compliance','₹2L'),('Tools + contingency','₹3L')]
for i,(a,b) in enumerate(cats):
 x=.8+(i%4)*3.05; y=2+(i//4)*2.0; card(s,x,y,2.75,1.35,a,b,LIGHT if i%2==0 else LAV); tx(s,x+.2,y+.75,2.3,.3,b,18,MINT,True)
s=slide('15 / Funding milestones','Raise in stages, based on evidence'); card(s,.8,2.0,3.7,2.8,'VALIDATION','₹15–20L\n30 paid orders\n30–40 active creators\n5 case studies\nFirst repeat customers'); card(s,4.8,2.0,3.7,2.8,'EARLY PMF','₹35–50L total\n250 completed orders\n35% repeat target\nTwo reliable channels\nFirst monthly customers',LAV); card(s,8.8,2.0,3.7,2.8,'EXPANSION','₹75L–₹1Cr+\nPaid acquisition works\nAgency/pod revenue\nStable quality and contribution',GOLD)
s=slide('16 / Recommendation','Build the loop before buying the scale'); tx(s,1.0,2.1,11.3,.8,'Run a focused Lucknow/NCR-led concierge pilot serving India remotely.',25,INK,True,PP_ALIGN.CENTER); card(s,1.0,3.5,3.4,1.7,'CUSTOMERS','Clear use case, fast shortlist and approved work'); card(s,4.95,3.5,3.4,1.7,'CREATORS','Fair scope, 100% subtotal payout and repeat demand',LAV); card(s,8.9,3.5,3.4,1.7,'BUSINESS','Measurable channels, healthy repeat and contribution visibility',GOLD); tx(s,1.0,6.1,11.3,.3,'Vinayak Tower, Vibhuti Khand, Lucknow 226028',10,MUTED,False,PP_ALIGN.CENTER)
prs.save(OUT); print(OUT)
