<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
return new class extends Migration {
 public function up(): void {
  if (DB::table('services')->where('slug','performance-marketing-monthly-management')->exists()) return;
  $creator=DB::table('creators')->where('is_verified',true)->orderByDesc('rating')->first(); if(!$creator) return;
  DB::table('services')->insert(['creator_id'=>$creator->id,'title'=>'Performance Marketing — Google + Meta Management','slug'=>'performance-marketing-monthly-management','description'=>'Monthly performance marketing management across Google Ads and Meta Ads. We align tracking, campaign structure, audiences, creative testing and reporting to your conversion goal. Ad spend is paid directly to the platforms and is not included.','cover'=>'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80','price'=>24999,'compare_price'=>34999,'mrp'=>34999,'delivery_days'=>30,'category'=>'Performance Marketing','profile_type'=>'hybrid','price_type'=>'paid','is_active'=>true,'is_barter'=>false,'deliverables'=>json_encode(['Tracking and account audit','Google and Meta campaign structure','Creative and audience testing plan','Monthly optimisation and reporting']),'revision_count'=>0,'billing_type'=>'monthly','monthly_price'=>24999,'scope'=>'One monthly management cycle across Google Ads and Meta Ads. Media spend, landing-page development and third-party tools are separate.','process'=>'Kickoff and tracking audit → campaign plan → launch or optimisation → weekly checks → monthly report.','faq_json'=>json_encode([['q'=>'Is ad spend included?','a'=>'No. Google and Meta charge media spend directly; the service fee is for management.'],['q'=>'Is this one-time?','a'=>'No. This is a monthly management package.']]),'seo_title'=>'Performance Marketing Agency Service | Google and Meta Ads','seo_description'=>'Monthly Google and Meta Ads management with tracking, campaign structure, creative testing, optimisation and reporting. Ad spend is separate.','aeo_answer'=>'GIG60 performance marketing is a monthly Google Ads and Meta Ads management service. It includes tracking review, campaign structure, testing, optimisation and reporting; ad spend is separate.','badge'=>'Growth','sold_count'=>0,'rating'=>4.8,'created_at'=>now(),'updated_at'=>now()]);
 }
 public function down(): void { DB::table('services')->where('slug','performance-marketing-monthly-management')->delete(); }
};
